---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library("ggplot2")
library("badger")
```

# gghist: Quickly draw a histogram using ggplot2

```{r, echo = FALSE, results='asis'}
cat(
	badge_cran_release("badger", "green"),
	badge_cran_download("badger", "grand-total", "green"),
	badge_cran_download("badger", "last-month", "green"),
	badge_cran_download("badger", "last-week", "green"),
	badge_github_actions()
)
```

gghist is a wrapper around ggplot2's `geom_histogram()` to easily plot a histogram of a numeric vector. This is especially useful, since `qplot()` was deprecated in ggplot2 3.4.0.

## Installation

You can install the current release from CRAN via

```r
install.packages("gghist")
```

or the development version from Github via

```r
devtools::install_github("frederikziebell/gghist")
```

## Example

```{r example}
library(gghist)

x <- rnorm(100)
gghist(x)

x <- exp(rnorm(1000))
gghist(x, bins = 100, fill = "firebrick") + 
  scale_x_log10()
```
